### ISSUE TITLE
Missing field in flow config

### ISSUE THREAD

**Issue by kimbaxz** [unioslo/kc-conditional-kerberos#1]
Hello, 

I've used keycloak version 24.0.4 and changed in the custom provider pom.xml the keycloak version to 24.0.4

I've tested your custom provider and got some problem, I can add the custom kerberos authentication flow, but I cannot set an IP rang, there is no field. 

Is this provider compatible with the version 24.0.4? 

Screenshot with missing field: 
![image](https://github.com/user-attachments/assets/47ee9cce-e836-4143-8489-dbe4005a1450)

I've inspected the page code, and there is no "input" field : 
![image](https://github.com/user-attachments/assets/fb5f42a2-cc27-4d43-bb59-9bc8a1cc62e8)

**Comment by oculos** [comment]
This is really strange! It should be compatible with 24.X, but I didn't test. You can modify the pom.xml to make it build against 24, just to check. But it is so weird that it doesn't show the options - as you see here: https://github.com/unioslo/kc-conditional-kerberos/blob/0b1d0790dd64b0eaedf4290c6d5cb50fb4595ef6/src/main/java/no/uio/keycloak/ConditionalKerberos/ConditionalKerberosFactory.java#L108, the code is there. I see no reason why it wouldn't show for you.

**Comment by kimbaxz** [comment]
I've made some tests: 

- With the build  already in the git: same probleme, no field when using keycloak version 24.0.4
- With a build against 24 (edited the pom.xml), same problem, no field show. 

I'll make try with a version 25.X of keycloak just to be sure I've done every steps correctly

**Comment by kimbaxz** [comment]
Just to add the information if anyone has the same problem.
I've just finished testing with a version 25.0.4 and another version 24.0.4 of keycloak. And unfortunately it's version 24.0.4 that isn't compatible.  

I've also tried to build the provider (after edited the pod.xml to set the version 24.04) and it's the same result. 


 But thanks you!
I'll try to use version 25.X of keycloak and your custom provider, because it solves a problem for my use-case.

**Comment by oculos** [comment]
> Just to add the information if anyone has the same problem. I've just finished testing with a version 25.0.4 and another version 24.0.4 of keycloak. And unfortunately it's version 24.0.4 that isn't compatible.
> 
> I've also tried to build the provider (after edited the pod.xml to set the version 24.04) and it's the same result.
> 
> But thanks you! I'll try to use version 25.X of keycloak and your custom provider, because it solves a problem for my use-case.

Thank you for testing!
This is really weird - I went to the documentation, and it seems that multiple values fields are supported at least since version 21: https://www.keycloak.org/docs-api/21.0.2/javadocs/org/keycloak/provider/ProviderConfigProperty.html

I have no clue what could be causing this, but since it works on 25.0.4 I won't use too much time to look at it. If someone comes with an explanation and a fix, I'll be happy to add it.
