### ISSUE TITLE
Missing ")" in ConditionalKerberos.java

### ISSUE THREAD

**Issue by kimbaxz** [unioslo/kc-conditional-kerberos#2]
Hello, 

Just in case, there is a missing ")" in the file "ConditionalKerberos.java" 

Error message : 
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project conditional-kerberos: Compilation failure
[ERROR] /[anonymised-path]/keycloak-quickstarts-25.0.4/extension/kc-conditional-kerberos/src/main/java/no/uio/keycloak/ConditionalKerberos/ConditionalKerberos.java:[51,57] ')' expected

if ((logout == null) || ((logout.equals("false")))

instead of 

if ((logout == null) || ((logout.equals("false"))))

**Comment by oculos** [comment]
I might have forgotten to push the latest version. Will do it soon.

Best,
Francis

**Comment by oculos** [comment]
This is now fixed.
